swagger: '2.0'

info:
  title: System status API
  description: System status information
  version: '0.0.2'

schemes:
- http
- https

produces:
- application/json

paths:
  /system/status:
    get:
      description: Get system status
      responses:
        200:
          description: success
          schema:
            $ref: '#/definitions/SystemStatus'
          examples:
            {
              "application/json": {
                $ref: '#/externalDocs/x-mocks/SystemStatusExample'
              }
            }
    put:
      parameters:
      - name: body
        in: body
        required: true
        schema:
          $ref: '#/definitions/SystemStatus'
      description: Update hostname
      responses:
        200:
          description: success
          schema:
            $ref: '#/definitions/SystemStatus'
          examples:
            {
              "application/json": {
                $ref: '#/externalDocs/x-mocks/SystemStatusExample'
              }
            }

  /system/reboot:
    post:
      description: 'Reboot system (delay: 3 sec)'
      responses:
        200:
          description: success

  /system/syslog:
    post:
      parameters:
      - name: body
        in: body
        required: true
        schema:
          $ref: '#/definitions/UrlInfo'
      description: Uplaod system logs to remote server
      responses:
        200:
          description: sucess
          schema:
            $ref: '#/definitions/UrlInfo'
          examples:
            {
              "application/json": {
                "url": "https://www.google.com"
              }
            }

  /network/interfaces:
    get:
      description: Get network interfaces
      responses:
        200:
          description: success
          schema:
            $ref: '#/definitions/NetworkInterfaces'
          examples:
            {
              "application/json": {
                $ref: '#/externalDocs/x-mocks/NetworkInterfacesExample'
              }
            }

  /system/password:
    put:
      parameters:
      - name: body
        in: body
        required: true
        schema:
          $ref: '#/definitions/SystemPassword'
      description: Update OS password
      responses:
        200:
          description: success

  /system/properties:
    get:
      description: Get system properties
      responses:
        200:
          schema:
            $ref: '#/definitions/SystemProperties'
          description: success
          examples:
            {
              "application/json": {
                $ref: '#/externalDocs/x-mocks/SystemPropertiesExample'
              }
            }

  /system/properties/{key}:
    parameters:
    - name: key
      in: path
      type: string
      required: true

    get:
      description: Get specific system property
      responses:
        200:
          schema:
            allOf:
            - $ref: '#/definitions/SystemProperties/properties/aliasName'
            - $ref: '#/definitions/SystemProperties/properties/gps'
          description: success
          examples:
            {
              "application/json": {
                $ref: '#/externalDocs/x-mocks/SystemPropertiesExample/gps'
              }
            }

    put:
      description: Update specific system property
      parameters:
      - name: body
        in: body
        required: true
        schema:
          $ref: '#/definitions/SystemPropertiesUpdate'
      responses:
        200:
          description: success
          examples:
            {
              "application/json": {
                $ref: '#/externalDocs/x-mocks/SystemPropertiesExample/gps'
              }
            }

definitions:
  SystemStatus:
    description: System status
    type: object
    properties:
      hostname:
        description: Hostname
        type: string
        minLength: 1
        maxLength: 63
        pattern: '/^(?![0-9]+$)(?!.*-$)(?!-)[a-zA-Z0-9-]{1,63}$/'
      version:
        description: Version of system
        type: string
        readOnly: true
      uptimeSec:
        description: 'System uptime (unit: seconds)'
        type: string
        readOnly: true
      cpuUsage:
        description: 'CPU usage (in percentage)'
        type: number
        readOnly: true
      memoryUsage:
        description: 'System memory usage (in percentage)'
        type: number
        readOnly: true
      memory:
        description: 'System total memory (unit: byte)'
        type: integer
        readOnly: true
      disks:
        type: array
        readOnly: true
        items:
          $ref: '#/definitions/Disk'
    example:
      $ref: '#/externalDocs/x-mocks/SystemStatusExample'

  Disk:
    description: Disk information
    type: object
    readOnly: true
    properties:
      name:
        description: Disk alias
        type: string
        readOnly: true
      mount:
        description: Mount point
        type: string
        readOnly: true
      device:
        description: Physical device node path
        type: string
        readOnly: true
      usage:
        description: Usage of this disk
        type: object
        readOnly: true
        properties:
          total:
            description: 'Total size (unit: byte)'
            type: integer
            readOnly: true
          used:
            description: 'Used size (unit: byte)'
            type: integer
            readOnly: true
          free:
            description: 'Free size (unit: byte)'
            type: integer
            readOnly: true
          percent:
            description: 'Percent of used size'
            type: number
            readOnly: true

  NetworkInterfaces:
    description: Network Interfaces
    type: array
    items:
      type: string
    example:
      $ref: '#/externalDocs/x-mocks/UrlInfoExample'

  UrlInfo:
    description: Url information
    type: object
    required:
    - url
    properties:
      url:
        description: Url address
        type: string
        minLength: 1
        maxLength: 4096
      headers:
        description: Headers
        type: object
    example:
      $ref: '#/externalDocs/x-mocks/UrlInfoExample'

  SystemPassword:
    description: System Password
    required:
    - password
    type: object
    properties:
      password:
        description: password
        type: string
        minLength: 4
        maxLength: 255
    example:
      $ref: '#/externalDocs/x-mocks/SystemPasswordExample'

  SystemProperties:
    description: System Properties
    type: object
    properties:
      aliasName:
        description: Alias name of this device
        type: string
        maxLength: 255
        default: 'MOXA IoT Gateway'
      gps:
        description: GPS location information
        type: object
        required:
        - lat
        - lng
        properties:
          lat:
            type: number
            format: float
            description: latitude
            default: 0
          lng:
            type: number
            format: float
            description: longitude
            default: 0
    example:
      $ref: '#/externalDocs/x-mocks/SystemPropertiesExample'

  SystemPropertiesUpdate:
    description: Request payload for updating system property
    type: object
    required:
    - data
    properties:
      data:
        type: object
        allOf:
        - $ref: '#/definitions/SystemProperties/properties/aliasName'
        - $ref: '#/definitions/SystemProperties/properties/gps'
    example:
      $ref: '#/externalDocs/x-mocks/SystemPropertiesUpdateExample'

externalDocs:
  url: '#'
  x-mocks:
    SystemStatusExample:
      {
        "hostname": "Moxa",
        "version": "1.1.0-1",
        "uptimeSec": 312956,
        "cpuUsage": 5.7,
        "memoryUsage": 63.8,
        "memory": 257286144,
        "disks": [
          {
            "name": "system",
            "mount": "/",
            "device": "rootfs",
            "usage": {
              "total": 770695168,
              "used": 497655808,
              "free": 217038848,
              "percent": 64.6
            }
          },
          {
            "name": "sd1",
            "mount": "/media/sd-mmcblk1p1",
            "device": "/dev/mmcblk1p1",
            "usage": {
              "total": 770695168,
              "used": 497655808,
              "free": 217038848,
              "percent": 64.6
            }
          }
        ]
      }

    UrlInfoExample:
      {
        "url": "https://server/upload",
        "headers": {
          "accessToken": "MOXAMOXA-TEST-SYSTEM"
        }
      }

    NetworkInterfacesExample:
      ["tunl0","eth0","eth1"]

    SystemPasswordExample:
      {"passowrd": "thisisyourpassword"}

    SystemPropertiesExample:
      {
        "gps": {
          "lat": 121.123,
          "lng": 22.456
        },
        "aliasName": "my iot gateway"
      }

    SystemPropertiesUpdateExample:
      {
        "data": {
          "lat": 121.123,
          "lng": 22.456
        }
      }
